image: node:8

before_script:
  - cd website
  - npm install

pages:
  script:
    - npm run build
    - cd ..
    - mkdir public
    - mv website/build/moe-site/* public
  artifacts:
    paths:
      - public
  only:
    - pages
