image: python:3.6

stages:
  - lint
  - test

before_script:
  - pip install -r config/requirements.txt

pylint:
  stage: lint
  script:
    - make pylint

flake8:
  stage: lint
  script:
    - make flake8

test:
  script:
    - make test
